### PR TITLE
adding java8 for mendix 6

### PR DESCRIPTION
**Pull request by RaphaelAudet**
Signed-off-by: Raphael Audet raphael.audet@mendix.com

### CODE REVIEW

**Comment by RaphaelAudet** [comment]
Maybe we should also remove java 7... what do you think @pommi ?

**Comment by pommi** [comment]
Agreed! Can you update the pull request?

**Comment by RaphaelAudet** [comment]
Ok, maybe you want to make a tag for the final version with java 7, if ever someone has a strong requirement for it

**Comment by RaphaelAudet** [comment]
Pull-Request updated, I removed java7, please merge :)

**Comment by pommi** [comment]
After merging I realized that you included oracle-java8u45-jre. We are not allowed to redistribute Oracle Java, so created a new commit and just replaced it by OpenJDK 8 (6ed8cda51ad78d2d78d5afebdc33ef858af92dcb).

**Comment by RaphaelAudet** [comment]
Ok so you've fixed it then, good job

**Pull request merged**
